### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by MarcoSavarin0** [sebastianbragam/MercadoLiebre#1]
1- Cumple
2- Cumple
3- se adapta, pero en version tablet se ve muy chico.
4- cumple
5- cumple
6- cumple
7- si es un formulario cumple
8- la unica animacion que falta es la del camion que gire a 90 grados
9- muy buena animacion la de pasar el cursor por encima de los productos y aparezca el nombre del producto de esa forma.
10-  le daria mas estetica en desktop al login y al register siento que ocupa mucho width.

**Comment by sebastianbragam** [comment]
Se cambió la animación a 90 grados.
