### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by valenMart1n** [sebastianbragam/MercadoLiebre#2]
-Cumple con el diseño y los elementos que se solicitan
-Los íconos del footer no se posicionan de manera correcta en la vista mobile
-La animación del camión no se muestra cuando se pasa el cursor sobre el elemento, sino que solo cuando se pasa el cursor sobre el dibujo

**Comment by sebastianbragam** [comment]
Se cambió la animación del camión para cuando se hace hover en todo el artículo. 

No entiendo qué es lo que está mal en el footer.

**Comment by sebastianbragam** [comment]
Se adaptó el footer a tamaño tablet y el ancho de los inputs.
