### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by chisator** [sebastianbragam/MercadoLiebre#3]
1- Cumple.
2- Cumple.
3- se adapta todo menos el footer.
4- Cumple.
5- Cumple.
6- Cumple.
7- Cumple.
8- Cumple todo menos el camión, pero hace otra animación, así que esta bueno. 
9- Me gusta la animación de los productos.
10- Podría cambiar el ancho de los input en el login y register.

**Comment by sebastianbragam** [comment]
Se adaptó el footer a tamaño tablet y el ancho de los inputs.
